theme = "sonokai" 

[editor]
line-number = "relative"
mouse = false
shell = ["sh"]
auto-completion = true
completion-trigger-len = 2

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
 
[editor.file-picker]
hidden = true
 
[keys.insert]
"left" = "move_char_left"
"right" = "move_char_right"
"up" = "move_line_up"
"down" = "move_line_down"